apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector: 
      matchLabels:
        name: postgres-pod
        type: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres-pod
        type: demo-voting-app

    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        port:
        - containersPort: 5432
  