apiVersion: apps/v1

kind: Deployment

metadata:
  name: redis-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector: 
      matchLabels:
        name: redis-pod
        type: demo-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis-pod
        type: demo-voting-app

    spec:
      containers:
      - name: redis
        image: redis
        port:
        - containersPort: 6379
  