apiVersion: apps/v1

kind: Deployment

metadata:
  name: result-app-deployment
  labels:
    app: demo-result-app
spec:
  replicas: 1
  selector: 
      matchLabels:
        name: result-app-pod
        type: demo-result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        app: result-app-pod
        type: demo-result-app

    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        port:
        - containersPort: 80
  